version: '3'

services:
  shopping-postgres:
    container_name: shopping-postgres
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_DATABASE=${DB_NAME}
    networks:
      - shopping-network
    ports:
      - '5432:5432'
    volumes:
      - 'shopping-pg-data:/bitnami/postgresql'
    networks:
      - shopping-network

  shopping:
    container_name: shopping
    build: .
    volumes:
      - '.:/user/node/shopping'
      - '/user/node/shopping/node_modules'
    ports:
      - '3000:3000'
      - '3333:3333'
    depends_on:
      - shopping-postgres
    networks:
      - shopping-network

volumes:
  shopping-pg-data:

networks:
  shopping-network:
    driver: bridge
